spring:
  application:
    name: mscards
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  h2:
    console:
      enabled: true
      path: /h2-console-mscards
    datasource:
      url: jdbc:h2:mem:testdb
      username: sa
      password:
      driverClassName: org.h2.Driver

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

mq:
  queues:
    create-cards: create-cards